project:
  type: website

website:
  title: "orsveri"
  navbar:
    background: primary
    search: true
    left:
      - about.qmd

  sidebar:
    style: "docked"
    contents:
      - section: "Avatar"
        contents:
          image: profile.jpg
      - section: "Links"
        contents:
          - icon: github
            href: https://github.com/orsveri
          - icon: linkedin
            href: https://linkedin.com/orsveri
format:
  html:
    theme: cosmo
    css: styles.css
    
execute:
  freeze: auto



