project:
  type: website

website:
  title: "orsveri"
  navbar:
    background: primary
    search: true
    left:
      - text: "About"
        file: about.qmd
      - text: "Tutorials"
        file: about.qmd

  sidebar:
    - title: "Tutorials"
      style: "docked"
      background: light
      contents:
        - image: profile.jpg
        - icon: github
          href: https://github.com/orsveri
        - icon: linkedin
          href: https://linkedin.com/orsveri
    
execute:
  freeze: auto



